### ISSUE TITLE
Dockerfile and images on docker hub are differents

### ISSUE THREAD

**Issue by albundy83** [bmarsh9/gapps#51]
Hello,
is it correct that images on docker hub are not built on the same way than the Dockerfile in this repository ?

I have try to use but I never have the same behaviour...
Can you help me on this please ?

**Comment by bmarsh9** [comment]
You are correct. I need to spend some time updating the docs and the repo with the most up to date code and so others can contribute. I haven’t had a great reason to do this yet… but now I do if others want to help.

**Comment by albundy83** [comment]
Hello,
I will be happy to help if needed

**Comment by OvrAp3x** [comment]
Would be great is this could be fixed, I saw you wrote on discord that you need to merge some code and create some automations. I have a bit of experience with the github automations, let me know if there are any blockers or somethign you need assistance with to make this happen. 
Would be really great to have the proper codebase here so that I and others can contribute more easily :-)

**Comment by bmarsh9** [comment]
Thanks @OvrAp3x - currently going through a very busy month of weddings and vacation. I’ll pick this ticket back up in a few weeks.

**Comment by OvrAp3x** [comment]
Greatly appreciated!

**Comment by bmarsh9** [comment]
Complete @OvrAp3x @albundy83
